language: php

php:
  - '7.4'

before_install:
  - nvm install --lts

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - node_modules

before_script:
  - yarn install
  - sudo mysql -e 'CREATE DATABASE homestead;'
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest --ignore-platform-reqs
  - cp .env.travis .env.testing

script:
  - yarn production
  - yarn lint
  - vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php --verbose --dry-run --diff
  - vendor/bin/phpunit --testdox

notifications:
  email: false
